FSP_jestkie_programisty/FSP_jestkie_programisty/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('main.urls')),
    path('about/', include('about.urls')),
    path('feedback/', include('feedback.urls')),
    path('catalog/', include('catalog.urls')),
    path('auth/', include('login.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
    path('admin/', admin.site.urls),
    path('chat/', include('ajax.urls')),
]

if settings.DEBUG:
    urlpatterns += (path('__debug__/', include('debug_toolbar.urls')),)
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

FSP_jestkie_programisty/ajax/urls.py
from django.urls import path, register_converter

from ajax import views

app_name = 'ajax'

urlpatterns = [
    path('', views.chat, name='chat'),
]

FSP_jestkie_programisty/catalog/urls.py
from django.urls import path, register_converter

from catalog import converters, views

register_converter(converters.Positive, 'pn')

app_name = 'catalog'

urlpatterns = [
    path('', views.item_list, name='item_list'),
    path('<int:pk>/', views.item_detail, name='item_detail'),
]

FSP_jestkie_programisty/main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.main, name='main'),
    path('coffee/', views.coffee, name='coffee'),
    path('parse/', views.parse, name='parse')
]

FSP_jestkie_programisty/templates/includes/footer.html
{% load static %}
<footer class="border-top text-center py-3">
    <div class="spinner-border text-primary" role="status">
        <span class="sr-only">©</span>
    </div>
    <p>
        <span id="year">{% now "Y" %}</span>&nbsp«Контора»
    </p>
    <script>
        var dateStr = "{% now "Y-m-d" %}T{% now "H:i:s" %}Z";
        var serverDate = Date.parse(dateStr);
        var now = Date.now();
        var diffTime = Math.abs(serverDate - now);
        var diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));

        var date = new Date(diffDays < 1 ? now : serverDate);

        $("#year").text(date.getFullYear());
    </script>
</footer>

FSP_jestkie_programisty/templates/includes/form.html
{% for field in form %}
  <div>
    {% for error in field.errors %}
      <div class="alert alert-danger">
        {{ error | escape }}
      </div>
    {% endfor %}
    {{ field.label_tag }} {{ field }}
    {% if field.help_text %}
      <p class="help">{{ field.help_text | safe }}</p>
    {% endif %}
  </div>
{% endfor %}

FSP_jestkie_programisty/templates/includes/header.html
{% load i18n %}
{% load static %}
<header>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {% with request.resolver_match.view_name as view_name %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url  'main:main' %}">
                <img src="{% static 'img/fav.jpg' %}">
            </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link {% if view_name == 'main:main' %}active" aria-current="page"
                        {% else %}
                        " href="{% url  'main:main' %}"
                        {% endif %}>
                            {% trans "Main" %}
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if view_name == 'about:about' %}active" aria-current="page"
                        {% else %}
                           " href="{% url 'about:about' %}"
                        {% endif %}>
                            {% trans "About" %}
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if view_name == 'catalog:item_list' %}active" aria-current="page"
                           {% else %}
                           " href="{% url  'catalog:item_list' %}"
                           {% endif %}>
                            {% trans "Catalog" %}
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if view_name == 'feedback:feedback' %}active" aria-current="page"
                        {% else %}
                            " href="{% url 'feedback:feedback' %}"
                        {% endif %}>
                            {% trans "Feedback" %}
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if view_name == '/admin/' %}active" aria-current="page"
                        {% else %}
                            " href="/admin/"
                        {% endif %}>
                            {% trans "Admin" %}
                        </a>
                    </li>
                    {% if user.is_authenticated %}
                        <li>User: {{ user.get_username }}</li>
                        <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
                        {% if user.profile.image %}
                            <img class="lazyOwl" data-src="{{ user.profile.image.url }}">
                        {% endif %}
                    {% else %}
                        <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% endwith %}
</header>

FSP_jestkie_programisty/templates/includes/item_card.html
{% with request.resolver_match.view_name as view_name %}
<li class="list-group-item">
    <a class="list-group-item list-group-item-action" href="{% url 'catalog:item_detail' item.pk %}">
        <div class="row">{{ item.name }}</div>
        {% if view_name != 'catalog:item_list' %}
        <div class="row">{{ item.level }}</div>
        {% endif %}
        <div class="row">{{ item.description | truncatewords_html:10 | safe }}</div>
        <div class="row">{{ item.budget }}</div>
        <div class="row">{{ item. }}</div>
    </a>
</li>
{% endwith %}